### PR TITLE
new: Fix global bin detection on windows.

### PR DESCRIPTION
**Pull request by sharpepd**
Update version to 0.13.1

Fix issue #1673

### CODE REVIEW

**Comment by milesj** [comment]
@sharpepd Just need to fix the formatting. Can run `yarn moon check --all` to see the errors.

**Comment by sharpepd** [comment]
I am not very familiar with this toolchain, but locally, I am getting errors in eslint due to a extension "moon" not being available.

Oops! Something went wrong! :(
         babel-preset:lint |
         babel-preset:lint | ESLint: 8.57.0
         babel-preset:lint |
         babel-preset:lint | ESLint couldn't find the config "moon" to extend from. Please check that the name of the config is correct.
         babel-preset:lint |
         babel-preset:lint | The config "moon" was referenced from the config file in "[...]\moon_dev\.eslintrc.js".

So I have made my best guess at the changes and pushed. Fingers crossed!

**Comment by milesj** [comment]
@sharpepd Hrmmm, maybe do a `yarn install` to ensure the deps are there?

**Comment by sharpepd** [comment]
> @sharpepd Hrmmm, maybe do a `yarn install` to ensure the deps are there?

I did that and still no luck. I cannot see where this "moon" dependency is coming from. It is certainly not found "node_modules". I was kind of hoping that using the moon task for linting, would do the job for me without any further set-up.

I did manage to find the linting errors and apply the fixes. So I hope this time the checks go through.

**Comment by milesj** [comment]
Awesome, looks good.

**Pull request merged**
